name: SQL to Go Lint
on: [workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thecampagnards/sql-to-go:master
    steps:
      - run: apk add git
      - uses: actions/checkout@v3
      - run: sql-to-go -sql-file db/migrations/*.up.sql -output-folder internal/db
      - run: git diff --exit-code
